### ISSUE TITLE
Error reported: Already grouping users with 1 rule set 

### ISSUE THREAD

**Issue by git-fern** [emmarichardson/local_autogroup#11]
I came across this error on one of our courses: https://www.screencast.com/t/4Tn1Yw3J5

The strange thing is that the course doesn't have any groups. When I click the "Continue" button, it kicks me out of the course.

Running Autogroup 2.4 (2018070300) on Moodle 3.5.3

Thanks.

**Comment by git-fern** [comment]
Groups mode = Separate Groups
Force = No 

This is a restored course. I wonder if that has something to do with it.

**Comment by emmarichardson** [comment]
Hmm…that is how all my courses are and I restore all the time.  Are you trying to duplicate a method that is already added?

Emma

Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037

**Comment by git-fern** [comment]
Hi Emma. I can't actually add any autogroup rules to the course.  The error message suggests that a rule already exists but I can't see or remove it.   The plugin is working fine in all our other courses. I can't seem to reproduce this problem in another course.

**Comment by emmarichardson** [comment]
Did you have an auto group rule in the course you restored from?

Emma

Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037

**Comment by ak4t0sh** [comment]
It seems that autogroup does not correctly handle roles removal.

Steps to reproduce : 

1. Create a role "issue-11"
2. In an autogroup set add this group in "Eligible Roles"
3. Remove the role
4. Reload the autogroup management page. It should crash.

I'll try to provide a patch ASAP.

**Comment by emmarichardson** [comment]
Thank you Arnaud!!

**Comment by ak4t0sh** [comment]
Waiting a proper fix (with an observer which will clean the eligible roles on role removal) you can deploy this patched version [https://github.com/ak4t0sh/local_autogroup/archive/cd501985e4576f9cf3e307012126e83a966321e6.zip](https://github.com/ak4t0sh/local_autogroup/archive/cd501985e4576f9cf3e307012126e83a966321e6.zip) 

Corresponding commit : [https://github.com/ak4t0sh/local_autogroup/commit/cd501985e4576f9cf3e307012126e83a966321e6](https://github.com/ak4t0sh/local_autogroup/commit/cd501985e4576f9cf3e307012126e83a966321e6).

It just prevent management page to crash.

**Comment by git-fern** [comment]
This patch cleared up the problem. Thank-you Arnaud.
