### ISSUE TITLE
Groupid in forums is not cleared

### ISSUE THREAD

**Issue by ned-code** [emmarichardson/local_autogroup#13]
Our site is experiencing a problem with forum groups and I suspect it's related to the autogroup plugin.  

In some courses (not all), groups are not applied to forums even though the course has forced-groups enabled. I tried to fix the problem by removing all groups from the course and allowing autogroup to rebuild them, but it looks like this process does not reset the forum groupid in the database, as shown here:  [https://www.screencast.com/t/KImDQKdh](https://www.screencast.com/t/KImDQKdh)

This info might help diagnose to issue:

1. The autogroup plugin is using the **Institution** field to generate groups. Last week, we changed the name of the institution for about 40 user profiles.  I suspect this may have something to do with the problem, but I could be wrong.

2. We changed "Institution" to "Campus" in the Moodle language string, but I doubt this has any impact on the way autogroup manages groups. 

3. All the event triggers are enabled, as shown here: [https://www.screencast.com/t/IBtucat7HsD9](https://www.screencast.com/t/IBtucat7HsD9)

Thanks!

**Comment by emmarichardson** [comment]
If you disable the plugin in the course, does it work as expected?  What version of Moodle/plugin?  I don't really think this plugin would affect that...

**Comment by ned-code** [comment]
- Moodle 3.5.4+ (Build: 20190124) 
- Autogroup 2.4 (Build: 2018070300)
- Also installed [this patch](https://github.com/ak4t0sh/local_autogroup/commit/cd501985e4576f9cf3e307012126e83a966321e6) about a month ago.

Disabling the plugin does not help. Neither does deleting and recreating the groups. The groupid for the forums is not cleared in the database. It could be unrelated to the autogroup plugin, in which case I apologize for the false alarm. Just thought it was worth mentioning here, since the problem seemed to arise after the user profile field was changed.

**Comment by ned-code** [comment]
This may also be helpful: 

Just tried to update and came across this error: 

_Notice: Undefined variable: dbman in /var/www/moodle/local/autogroup/db/upgrade.php on line 34
Exception - Call to a member function table_exists() on null_

[https://www.screencast.com/t/iPzm0X6PL](https://www.screencast.com/t/iPzm0X6PL)

**Comment by ned-code** [comment]
I continue to experience this issue on our Moodle site.  My latest thinking is that this problem happens because **Autogroup messes up the GROUPS IDs in forums (and possibly other activities) when the user 
_role name_ is changed at the site level**. I need to do more testing to eliminate other factors, but would appreciate it if others could give it a try as well. It would make me feel slightly less crazy if this problem could be verified by someone else :)

These steps should reproduce the problem. Please don't try this on a production server. 

Create (or go) to a test course that has the following features:
1. Forced groups is turned on in course settings
2. Autogroup is active and sorts enrolled students into multiple groups
3. A forum is present with posts/replies from users in different groups

Now to reproduce the problem:
1. Go to _Site Admin > Users > Permissions > Define roles_ and rename the student role (example: student_1) 
2. Return to the course and check the forum.  Note that (some?) students are no longer in their groups. Moreover, if you take a look at the mdl_fourm_discussion table in the database, you should notice that the GROUP IDs for that forum are now either incorrect or missing. 
3. Extra step: Delete all groups in the course and have Autogroups recreate them. Then check the forum again. Note that this doesn't fix the problem.  

It's also possible that this could be a Moodle bug (not Autogroup) or possibly a conflict with another plugin.  More testing is needed. 

Thanks.

**Comment by emmarichardson** [comment]
Sorry, I am checking to see if I can find someone to help work on this plugin - if by chance, you have found a fix, please put in a pull request.

**Comment by ned-code** [comment]
Ok. I will see if I can find a developer to take a look.

**Comment by ned-code** [comment]
It looks like same problem (with forums) occurs if the profile field (which is used by autogroups) is changed after the student has posted to forums.  

For example, if the city profile field is used to create groups and the city of a user is changed after she posts to a forum, the group will not not get updated in the forum. It will just disappear.

**Comment by ned-code** [comment]
This scenarios described above will replicated the problem, but the actual cause is as follows: 

**_Moodle handles course groups and forum groups separately. If a group doesn’t have any members, Autogroup will delete the course group but it does not delete/update the groups associated with forum posts. As a result, forum posts associated with the old groups will point to groups that no longer exist._**

A fix for this problem can be found here: https://github.com/ned-code/local_autogroup/pull/1 (thanks Sergei Porfenovich). **This code has not been tested.**  Looking for testers to verify.

**Comment by emmarichardson** [comment]
I will test but it might not be right away.  I am buried with the start of the year.  If others can test and report back, that would be awesome.

Emma

Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037

**Comment by ak4t0sh** [comment]
Not tested yet but PR seems ok. 
I just asked sergei to open PR on this repo. Once done I’ll do a proper code review.

**Comment by emmarichardson** [comment]
Thanks Arnaud - if you find it to be ok, I am happy to merge it.  Just let me know when you get a chance to review.  I will try and find some testing time too but won’t hold it up if you find it acceptable.

Emma

Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037

**Comment by ned-code** [comment]
The PR can be found here https://github.com/emmarichardson/local_autogroup/pull/17
