### ISSUE TITLE
Group by default is unexpected

### ISSUE THREAD

**Issue by gbrewste** [emmarichardson/local_autogroup#16]
When an auto group is edited, the Group by field always defaults to the custom profile field that was created first. The expected behavior is that the Group by setting would default to the profile field that is being used by that group. IF the user is not paying much attention, they could actually change the profile field without realizing. Let me know if you need any additional clarification.

Geoff Brewster
geoffrey.brewster@ethinkeducation.com

**Comment by emmarichardson** [comment]
Sorry for the slow response - I will see if someone can take a look.  If you have a fix for it, please put a pull request.

**Comment by ak4t0sh** [comment]
Thanks for reporting this issue. I was able to reproduce it.
I’ll try to look at it but as @emmarichardson said if in the mean time you already fixed it do not hesitate to fill a PR. :)
