### ISSUE TITLE
GDPR compatibility

### ISSUE THREAD

**Issue by OlenaTatarintseva** [emmarichardson/local_autogroup#18]
Hello, 
​
It looks like the plugin local_autogroup is not compliant with GDPR. The plugin does not implement the Privacy API. Would you please implement it?
​
​Best regards,
Olena Tatarintseva

**Comment by emmarichardson** [comment]
I am not sure what you would expect here.  We are just creating groups...

**Comment by emmarichardson** [comment]
If you have the time to write the necessary code, please feel free to put in a pull request and we will review it.  Thanks.

**Comment by ak4t0sh** [comment]
local_autogroup does not store user data. It's only rely on data from Moodle core. So we should implement `null_provider`.
https://docs.moodle.org/dev/Privacy_API#Plugins_which_do_not_store_personal_data

**Comment by petersistrom** [comment]
Hi @emmarichardson 
Bumping this issue, as we would like to use your plugin but require GDPR compliance. I have added a privacy provider to make the plugin compliant with GDPR, could you please review when you get a chance? 
Thanks,
Peter
