### ISSUE TITLE
invalid get_string('manager', 'totara_hierarchy') in local_autogroup v2.4.1 for Totara 12

### ISSUE THREAD

**Issue by lmalysa** [emmarichardson/local_autogroup#21]
Hi, it seems that get_string('manager', 'totara_hierarchy') is invalid as there no such a string in totara_hierarchy lang file.
Problem found in Totara 12 and newest local_autogroup, however probably it is not a new problem.

The trace is as follows:

Invalid get_string() identifier: 'manager' or component 'totara_hierarchy'. Perhaps you are missing $string['manager'] 

    line 356 of /lib/classes/string_manager_standard.php: call to debugging()
    line 7496 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
    line 118 of /local/autogroup/classes/sort_module/primary_position.php: call to get_string()
    line 102 of /local/autogroup/settings.php: call to local_autogroup\sort_module\primary_position->get_config_options()
    line 67 of /lib/classes/plugininfo/local.php: call to include()
    line 605 of /admin/settings/plugins.php: call to core\plugininfo\local->load_settings()
    line 8073 of /lib/adminlib.php: call to require()
    line 7911 of /lib/adminlib.php: call to admin_get_root()
    line 11 of /admin/blocks.php: call to admin_externalpage_setup()

Kind regards,
Łukasz

**Comment by ak4t0sh** [comment]
Thanks for reporting this issue.
It appears that same issue has been reported with Totara 11 in #9.
Current maintainers do not have Totara to work on this issue but if you fixed it do not hesitate to fill a PR we'll merge it :)
