### ISSUE TITLE
Can't find course settings of module on Moodle 3.5.11

### ISSUE THREAD

**Issue by dlnsk** [emmarichardson/local_autogroup#24]
Can't find course settings (second screenshot on moodle plugin's page).
Only way to add auto groups to course is direct link:
https://"yoursite"/local/autogroup/manage.php?courseid=“yourcourseid"

**Comment by emmarichardson** [comment]
What theme are you using?  Have you changed to Boost?  It is found under Course/Users/Groups/Autogroups

**Comment by dlnsk** [comment]
Something strange with clearing cache while module installing. After I opened direct link menu item under Groups appear everywhere.
