### ISSUE TITLE
Error on stdClass::$hidepicture bitnami moodle 3.11

### ISSUE THREAD

**Issue by Ferrox85** [emmarichardson/local_autogroup#29]
I am using bitnami 3.11 moodle image. When adding or deleting a user I get this error:

Notice: Undefined property: stdClass::$hidepicture in /bitnami/moodle/local/autogroup/classes/domain/group.php on line 208

Possible an error with 3.11 version of moodle?

**Comment by emmarichardson** [comment]
I just tested this with 3.11.  Installed, added to course, set up.  Added new user to course and they were automatically added to group.  Created a new user at site level and then deleted user.  Zero errors with full debugging turned on.  Guessing it is something with the bitnami image or a clash with another plugin unless the way you have it set up is causing something - maybe try with pure Moodle install or default theme?  I just used the default auto group settings with Institution field as the trigger.  If you are using different settings, let me know what they are and I can test again.
Emma Richardson

**Comment by Ferrox85** [comment]
Thanks for your quick reaction! I am realizing I was not complete in my way of adding users after your awnser.

I am using the "upload users" function (i need to upload 100+ users at a time) in moodle

The upload works fine but generates this error line for over 200 times (with uploading one user). I am not very good at debugging this in moodle :-)

We are planning to migrate to this container set-up. But the plugin in 3.10 works fine (no errors at al) I can update this envoirement to 3.11 and test there if it generates the same error.. I'll report on this later.

**Comment by emmarichardson** [comment]
Just tested the upload users - also no error…do you have a plugin that affects groups at all?  It is strange that it is looking for an image...
Emma Richardson
Distance Learning Coordinator
Direct: 719-771-4022
***@***.***

**Comment by Ferrox85** [comment]
My other installed plugins:

Activity modules
Custom certificatemod_customcert | 3.11.12021051701 | Enabled | Settings | Uninstall | Additional
Reengagementmod_reengagement | 3.6.22019052800 | Enabled |   | Uninstall | Additional
Subcoursemod_subcourse | 9.0.12020090602 | Enabled |   | Uninstall | Additional

Custom certificate / customcertelement
Background image customcertelement_bgimage | 2021051700 |   |   |   | Additional
Borde rcustomcertelement_border | 2021051700 |   |   |   | Additional
Category name customcertelement_categoryname | 2021051700 |   |   |   | Additional
Code customcertelement_code | 2021051700 |   |   |   | Additional
Course field customcertelement_coursefield | 2021051700 |   |   |   | Additional
Course name customcertelement_coursename | 2021051700 |   |   |   | Additional
Date customcertelement_date | 2021051700 |   |   |   | Additional
Date range customcertelement_daterange | 2021051700 |   |   |   | Additional
Digital signature customcertelement_digitalsignature | 2021051700 |   |   |   | Additional
Grade customcertelement_grade | 2021051700 |   |   |   | Additional
Grade item name customcertelement_gradeitemname | 2021051700 |   |   |   | Additional
Image customcertelement_image | 2021051700 |   |   |   | Additional
QR code customcertelement_qrcode | 2021051700 |   |   |   | Additional
Student name customcertelement_studentname | 2021051700 |   |   |   | Additional
Teacher name customcertelement_teachername | 2021051700 |   |   |   | Additional
Text customcertelement_text | 2021051700 |   |   |   | Additional
User field  customcertelement_userfield | 2021051700 |   |   |   | Additional
User picturecustomcertelement_userpicture | 2021051700 |   |   |   | Additional

Blocks
Advanced notifications block_advnotifications | v1.3.122020101317 | Enabled | Settings | Uninstall | Additional
Coupon block_coupon | 4.0.7 (build 2020010807)2020010807 | Enabled | Settings | Uninstall | Additional

Enrolment methods
Auto enrolment enrol_auto | schoemansville-r12019022000 | Disabled | Settings | Uninstall | Additional

Authentication methods
Email-based self-registration with admin confirmation auth_emailadmin | 1.4.52030061000 | Enabled | Settings |   | Additional
Enrolment key based self-registration auth_enrolkey | 20200114002020011400 | Disabled | Settings | Uninstall | Additional

Admin tools
Upload enrolment methods tool_uploadenrolmentmethods | 1.3.3 (Build: 2021050800)2021050800 | Enabled |   | Uninstall | Additional

Local plugins
Auto Group local_autogroup | 2.52020072700 |   |   | Uninstall | Additional
Auto-cohort plugin local_cohortauto | 1.02021042700 |   |   | Uninstall | Additional

Having problems to test on the old server due to a PHP update. This is a live server so I can't test it right away..

**Comment by Ferrox85** [comment]
We've found out that an update of the database to version 3.11 removes the hidepicture collumn.

See the following link here:

https://github.com/moodle/moodle/blob/master/group/upgrade.txt

Probably is the error a result of an upgrade, not a fresh installation?

**Comment by emmarichardson** [comment]
Ah, so it looks like an issue with existing groups created by auto group because the column is also missing in the new 3.11.  I think the problem is that auto group has that field as protected - could you try commenting out the two references in the referenced file and then try again and see if that helps?  I am guessing the protected status is not allowing the column to be deleted maybe...

**Comment by Ferrox85** [comment]
Wich lines exactly?
2449 and 2450? And then before upgrading the database a assume?

I am not sure what you mean..

**Comment by emmarichardson** [comment]
Well I was looking at the classes/domain/group.php file which was referenced which only has about 300 lines.  In that file, try removing ‘hidepicture’, from line 253 and commenting out line 293.  Also, in the autogroup_set.php file, comment out line 409.  Each of those lines should reference the hidepicture column. Then, upgrade the database.  Report back.

Emma Richardson

**Comment by Ferrox85** [comment]
I've commented out the lines and reference you mentioned.

I've lost the original error, uploading a user seems to work fine and no error anymore when deleting a user.
But I still get an error when uploading.

Complete error:

Exception encountered in event observer '\local_autogroup\event_handler::role_change': This ID number is already in use
line 131 of /local/autogroup/classes/domain/group.php: call to groups_create_group()
line 413 of /local/autogroup/classes/domain/autogroup_set.php: call to local_autogroup\domain\group->create()
line 302 of /local/autogroup/classes/domain/autogroup_set.php: call to local_autogroup\domain\autogroup_set->get_or_create_group_by_idnumber()
line 100 of /local/autogroup/classes/domain/course.php: call to local_autogroup\domain\autogroup_set->verify_user_group_membership()
line 80 of /local/autogroup/classes/domain/user.php: call to local_autogroup\domain\course->verify_user_group_membership()
line 64 of /local/autogroup/classes/usecase/verify_user_group_membership.php: call to local_autogroup\domain\user->verify_user_group_membership()
line 231 of /local/autogroup/classes/event_handler.php: call to local_autogroup\usecase\verify_user_group_membership->__invoke()
line ? of unknownfile: call to local_autogroup\event_handler::role_change()
line 155 of /lib/classes/event/manager.php: call to call_user_func()
line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
line 834 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
line 996 of /admin/tool/uploaduser/classes/process.php: call to core\event\base->trigger()
line 331 of /admin/tool/uploaduser/classes/process.php: call to tool_uploaduser\process->process_line()
line 92 of /admin/tool/uploaduser/index.php: call to tool_uploaduser\process->process()

I've deleted the created user (due to the ID error) and tryed again. Still the same error.

Any hint what to do next?

**Comment by emmarichardson** [comment]
Try deleting the group/s that were probably created in one of your other attempts.

Emma Richardson
Distance Learning Coordinator
Direct: 719-771-4022
***@***.***

**Comment by Ferrox85** [comment]
Hi Emma,

It was a original database from before updating to 3.11. I've restored that database before uploading a new user as a test resulting in this error. All the other attempts for debugging this issue where erased by restoring the orignal 3.10 database. And considering there are over 500 groups in my live site this isn't an option in my opninion?

**Comment by emmarichardson** [comment]
But the upload works despite the error?  I am not sure why It is looking for an event handler…

Emma Richardson
Distance Learning Coordinator
Direct: 719-771-4022
***@***.***

**Comment by Ferrox85** [comment]
Yeah it seems to work, i'll recieve a welcome mail and I can log in with the test user. The user is not rolled out yet in a course.. is that causing the issue?

The rollout is done by upload enrolments method after uploading the users. When these are grouped together with auto_group.
I'dont know moodle development good enough for debugging it myself.. In version 3.10 it all works as it should..

**Comment by emmarichardson** [comment]
So you are not enrolling them in a course with the upload file?  Not listing any groups?
Emma Richardson
Distance Learning Coordinator
Direct: 719-771-4022
***@***.***

**Comment by Ferrox85** [comment]
No, these are the fields we are uploading:

username;firstname;lastname;email;institution;country;profile_field_locatie;profile_field_versie;profile_field_code_beheerder;profile_field_rol;lang

We have autocohort to make cohorts:
https://moodle.org/plugins/local_cohortauto

**Comment by emmarichardson** [comment]
And are you specifying the userid in the upload file?  In which case, did you delete the user from the database or just through the Moodle site?  If you are specifying the userid, then you have to delete the user actually from the database as deleting through Moodle, does not remove the entry from the database…

Emma Richardson
Distance Learning Coordinator
Direct: 719-771-4022
***@***.***

**Comment by Ferrox85** [comment]
We are not specifying an ID in the upload, just those collumns I mentioned.
I deleted the user with the moodle site, not in the database indeed.
But it was a completely new user, never used before in this site. I even tested with an other mail adres and username.. stil the same error.

**Comment by Ferrox85** [comment]
It gets the state NEW USER after the upload

![image](https://user-images.githubusercontent.com/64791738/125078490-bf23be00-e0c2-11eb-97ae-ad2077c51614.png)

**Comment by Ferrox85** [comment]
Hi Emma,

Any update on this?

Thanks in advance!

**Comment by emmarichardson** [comment]
Taking a look at this again.  In 4.0 I am now receiving the hidepicture error.  Still not sure on the id error - but it looks more like the group id is the problem.  If you are still having issues, please create a separate issue for that.
