### ISSUE TITLE
Upgrading from 2.8 to 2.8.1 (PostgreSQL 12)

### ISSUE THREAD

**Issue by caiadogithub** [emmarichardson/local_autogroup#46]
Informações de depuração:  ERROR: syntax error at or near "JOIN"
LINE 1: DELETE FROM mdl_local_autogroup_manual LAM JOIN mdl_groups G...
^
DELETE FROM mdl_local_autogroup_manual LAM JOIN mdl_groups G ON (G.id = LAM.groupid) WHERE G.idnumber NOT LIKE $1 ESCAPE '\'
-- line 97 of /local/autogroup/db/upgrade.php: call to pgsql_native_moodle_database->execute()
[array (
0 => 'autogroup|%',
)]
Error code: dmlwriteexception
Rastreamento de pilha: 

    line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
    line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
    line 338 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->read_slave_query_end()
    line 836 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
    line 97 of /local/autogroup/db/upgrade.php: call to pgsql_native_moodle_database->execute()
    line 703 of /lib/upgradelib.php: call to xmldb_local_autogroup_upgrade()
    line 1929 of /lib/upgradelib.php: call to upgrade_plugins()
    line 713 of /admin/index.php: call to upgrade_noncore()

**Comment by ak4t0sh** [comment]
Fix in 2.8.2 now available in Moodle plugin database. 
https://moodle.org/plugins/local_autogroup/2.8.2/28892

**Comment by caiadogithub** [comment]
> Fix in 2.8.2 now available in Moodle plugin database. https://moodle.org/plugins/local_autogroup/2.8.2/28892

Update to 2.8.2 ok!
