### ISSUE TITLE
memory leak in huge sites

### ISSUE THREAD

**Issue by danielavetica** [emmarichardson/local_autogroup#5]
Whenever this plugin is used in an huge site (in my case more than 10.000 users, and around 1000 courses) this plugin gets out of memory. 
This has has to do with the public function __construct in which the " $this->enrolledusers = \get_enrolled_users($this->context);" get called.  This is not used in the used event handler.

When replaced to the function "verify_all_group_membership" plugin works fine again...
starting from Rule 92:

```php 
public function verify_all_group_membership(\moodle_database $db)
    {
        $result = true;

        $enrolledusers = \get_enrolled_users($this->context , '' , 0 , 'u.id');
        foreach ($enrolledusers as $user){
            $result &= $this->verify_user_group_membership($user, $db);
        }

        return $result;
    }
```

the public function __construct will then be as follows:

```php
    public function __construct ($course, \moodle_database $db)
    {
        //get the id for this course
        $this->parse_course_id($course);

        $this->context = \context_course::instance($this->id);

        //load autogroup groups for this course
        $this->get_autogroups($db);
    }
```

**Comment by luukverhoeven** [comment]
@emmarichardson @danielavetica I submitted a pull request.

**Comment by emmarichardson** [comment]
Sorry this took me so long to get to but I did finally get it tested and merged.  Will update Moodle database today.
