### ISSUE TITLE
Release for Moodle 4.5 LTS

### ISSUE THREAD

**Issue by michael-milette** [emmarichardson/local_autogroup#58]
Hi,

When do you expect to have a version of this very useful plugin ready for Moodle 4.5 LTS?

Best regards,

Michael Milette

**Comment by emmarichardson** [comment]
I have it running on 4.5 and have not seen any issues yet.  I will try and do some more testing but I am pretty sure it is good as is.

**Comment by SolutionsDEV** [comment]
It installed without issues, but in a course it returns errors. This is in Moodle 4.5.

**Comment by emmarichardson** [comment]
Oh, sorry, I realized that I had it on a site that I had not tested fully with.  You are correct.  I will start looking into it.

**Comment by emmarichardson** [comment]
@ak4t0sh Do you have time to look at this - it appears that autogroup is referencing a library that Moodle has deprecated - lib/outputrenderers.php...

**Comment by SolutionsDEV** [comment]
Hi Emma,

Thanks for your reply. When adding to course, it returns this error (developer debug)

![image](https://github.com/user-attachments/assets/61ae7285-0c78-4481-9c81-0c3fbddce794)

On the other hand, it would be nice to add something that affects current existing courses, either when saving or with a button to trigger it.
![image](https://github.com/user-attachments/assets/872c7752-697c-454e-a8b8-a16113f0a195)

Thanks a lot

**Comment by ak4t0sh** [comment]
@emmarichardson I think I can work on it this week.

**Comment by emmarichardson** [comment]
Thank you, @ak4t0sh

**Comment by emmarichardson** [comment]
I have added the new release to Moodle plugins.  Also included a pull request implementing CLI tool.  Thanks for looking at this so quickly.

**Comment by michael-milette** [comment]
Thank you for the update!
